services:
  wso2is:
    image: wso2/wso2is:7.0.0
    ports:
      - "9443:9443"
    networks:
      - wso2-network
    volumes:
      - ./repository/conf/deployment.toml:/home/wso2carbon/wso2is-7.0.0/repository/conf/deployment.toml
      - ./repository/components/lib/postgresql-42.7.5.jar:/home/wso2carbon/wso2is-7.0.0/repository/components/lib/postgresql-42.7.5.jar
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=
    networks:
      - wso2-network
  
  caddy:
    build:
      context: ./caddy
    expose:
      - 2019:2019/tcp
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wso2is
    networks:
      - wso2-network
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile

networks:
  wso2-network:
    driver: bridge
    external: true