version: '3.8'

services:
  wso2is:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "9443:9443"
    networks:
      - wso2-network

networks:
  wso2-network:
    driver: bridge
    external: true