version: '3.8'

services:
  wso2is:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "9443:9443"
    networks:
      - wso2-network
    volumes:
      - ./repository/conf/deployment.toml:/app/repository/conf/deployment.toml

networks:
  wso2-network:
    driver: bridge
    external: true