services:
  wso2is:
    image: wso2/wso2is:7.0.0
    ports:
      - "9443:9443"
    networks:
      - wso2-network
    volumes:
      - ./repository/conf/deployment.toml:/home/wso2carbon/wso2is-7.0.0/repository/conf/deployment.toml
      - ./repository/components/lib/postgresql-42.7.5.jar:/home/wso2carbon/wso2is-7.0.0/repository/components/lib/postgresql-42.7.5.jar
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok/ngrok-secrets.yml,/etc/ngrok/ngrok.yml"
    volumes:
      - ./ngrok:/etc/ngrok
    networks:
      - wso2-network
    ports:
      - 4040:4040
    

networks:
  wso2-network:
    driver: bridge
    external: true